name: flying_characters
description: A flutter package to animate flying characters or particles on screen.
version: 1.0.3
homepage: https://github.com/ASHISH1317/flying_characters
repository: https://github.com/ASHISH1317/flying_characters
issue_tracker: https://github.com/ASHISH1317/flying_characters/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/character_fly.gif
    - assets/word_fly.gif
